/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register with phone, name, and password.
         */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login with phone and password.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Request a password reset code.
         */
        post: operations["postAuthForgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset password using a valid token.
         */
        post: operations["postAuthReset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Sign-In
         * @description Authenticate using Google ID token.
         */
        post: operations["postAuthGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Sign-In
         * @description Authenticate using Apple identity token.
         */
        post: operations["postAuthApple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Tokens
         * @description Rotate access and refresh tokens.
         */
        post: operations["postAuthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate a refresh token session.
         */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getUsersMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile */
        patch: operations["patchUsersMe"];
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload avatar image */
        post: operations["postUsersMeAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/device-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register device push token */
        post: operations["postUsersMeDevice-token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search user by phone number */
        get: operations["getUsersSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a user */
        post: operations["postUsersByUserIdBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all accepted friends with net balances */
        get: operations["getFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pending friend requests */
        get: operations["getFriendsRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a friend request */
        post: operations["postFriendsRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Accept a friend request */
        patch: operations["patchFriendsByIdAccept"];
        trace?: never;
    };
    "/friends/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Decline a friend request */
        patch: operations["patchFriendsByIdDecline"];
        trace?: never;
    };
    "/friends/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove friend or cancel request */
        delete: operations["deleteFriendsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite a non-app user by phone */
        post: operations["postFriendsInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all user groups */
        get: operations["getGroups"];
        put?: never;
        /** Create a new group */
        post: operations["postGroups"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/join/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Join group via invite token */
        get: operations["getGroupsJoinByToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group details */
        get: operations["getGroupsById"];
        put?: never;
        post?: never;
        /** Archive group */
        delete: operations["deleteGroupsById"];
        options?: never;
        head?: never;
        /** Update group info */
        patch: operations["patchGroupsById"];
        trace?: never;
    };
    "/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add members to group */
        post: operations["postGroupsByIdMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove member or leave group */
        delete: operations["deleteGroupsByIdMembersByUserId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/members/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update member role */
        patch: operations["patchGroupsByIdMembersByUserIdRole"];
        trace?: never;
    };
    "/groups/{id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate group invite link */
        post: operations["postGroupsByIdInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/invite/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke invite link */
        delete: operations["deleteGroupsByIdInviteByInviteId"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user notifications */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get unread notification count */
        get: operations["getNotificationsUnread-count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark all notifications as read */
        patch: operations["patchNotificationsRead-all"];
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark specific notification as read */
        patch: operations["patchNotificationsByIdRead"];
        trace?: never;
    };
    "/groups/{id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group expenses (paginated) */
        get: operations["getGroupsByIdExpenses"];
        put?: never;
        /** Create expense in group */
        post: operations["postGroupsByIdExpenses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group balances */
        get: operations["getGroupsByIdBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get expense detail */
        get: operations["getExpensesById"];
        put?: never;
        post?: never;
        /** Soft delete expense */
        delete: operations["deleteExpensesById"];
        options?: never;
        head?: never;
        /** Edit expense (creator or admin) */
        patch: operations["patchExpensesById"];
        trace?: never;
    };
    "/expenses/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload receipt image */
        post: operations["postExpensesReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's overall balances */
        get: operations["getUsersMeBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group settlements (paginated) */
        get: operations["getGroupsByIdSettle"];
        put?: never;
        /** Record a settlement in group */
        post: operations["postGroupsByIdSettle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settlements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete settlement (payer or admin) */
        delete: operations["deleteSettlementsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    password: string;
                    name: string;
                };
                "application/x-www-form-urlencoded": {
                    phone: string;
                    password: string;
                    name: string;
                };
                "multipart/form-data": {
                    phone: string;
                    password: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Response for status 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            access_token: string;
                            refresh_token: string;
                            is_new_user: boolean;
                            user: {
                                id: string;
                                phone: (string | null) | null;
                                name: string;
                                avatar_url: (string | null) | null;
                            };
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Response for status 422 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    password: string;
                };
                "application/x-www-form-urlencoded": {
                    phone: string;
                    password: string;
                };
                "multipart/form-data": {
                    phone: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            access_token: string;
                            refresh_token: string;
                            is_new_user: boolean;
                            user: {
                                id: string;
                                phone: (string | null) | null;
                                name: string;
                                avatar_url: (string | null) | null;
                            };
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    "postAuthForgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                };
                "application/x-www-form-urlencoded": {
                    phone: string;
                };
                "multipart/form-data": {
                    phone: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    "postAuthReset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    new_password: string;
                };
                "application/x-www-form-urlencoded": {
                    token: string;
                    new_password: string;
                };
                "multipart/form-data": {
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
            /** @description Response for status 422 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    postAuthGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id_token: string;
                };
                "application/x-www-form-urlencoded": {
                    id_token: string;
                };
                "multipart/form-data": {
                    id_token: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            access_token: string;
                            refresh_token: string;
                            is_new_user: boolean;
                            user: {
                                id: string;
                                phone: (string | null) | null;
                                name: string;
                                avatar_url: (string | null) | null;
                            };
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    postAuthApple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    identity_token: string;
                    full_name?: string;
                };
                "application/x-www-form-urlencoded": {
                    identity_token: string;
                    full_name?: string;
                };
                "multipart/form-data": {
                    identity_token: string;
                    full_name?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            access_token: string;
                            refresh_token: string;
                            is_new_user: boolean;
                            user: {
                                id: string;
                                phone: (string | null) | null;
                                name: string;
                                avatar_url: (string | null) | null;
                            };
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    postAuthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                    device_info?: string;
                };
                "application/x-www-form-urlencoded": {
                    refresh_token: string;
                    device_info?: string;
                };
                "multipart/form-data": {
                    refresh_token: string;
                    device_info?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            access_token: string;
                            refresh_token: string;
                            is_new_user: boolean;
                            user: {
                                id: string;
                                phone: (string | null) | null;
                                name: string;
                                avatar_url: (string | null) | null;
                            };
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
                "application/x-www-form-urlencoded": {
                    refresh_token: string;
                };
                "multipart/form-data": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description Response for status 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: false;
                        error: {
                            code: string;
                            message: string;
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    getUsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            phone: (string | null) | null;
                            email: (string | null) | null;
                            avatarUrl: (string | null) | null;
                            upiId: (string | null) | null;
                            preferredCurrency: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchUsersMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                    phone?: string;
                    upiId?: string;
                    preferredCurrency?: string;
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                    phone?: string;
                    upiId?: string;
                    preferredCurrency?: string;
                };
                "multipart/form-data": {
                    name?: string;
                    /** Format: email */
                    email?: string;
                    phone?: string;
                    upiId?: string;
                    preferredCurrency?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            phone: (string | null) | null;
                            email: (string | null) | null;
                            avatarUrl: (string | null) | null;
                            upiId: (string | null) | null;
                            preferredCurrency: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    postUsersMeAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "application/x-www-form-urlencoded": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            avatarUrl: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    "postUsersMeDevice-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** @enum {string} */
                    platform: "android" | "ios" | "web";
                    deviceInfo?: string;
                };
                "application/x-www-form-urlencoded": {
                    token: string;
                    /** @enum {string} */
                    platform: "android" | "ios" | "web";
                    deviceInfo?: string;
                };
                "multipart/form-data": {
                    token: string;
                    /** @enum {string} */
                    platform: "android" | "ios" | "web";
                    deviceInfo?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getUsersSearch: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            avatarUrl: (string | null) | null;
                            isAlreadyFriend: boolean;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    postUsersByUserIdBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getFriends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            avatarUrl: (string | null) | null;
                            phone: (string | null) | null;
                            upiId: (string | null) | null;
                            netBalance: number;
                            currency: string;
                        }[];
                        message: string;
                    };
                };
            };
        };
    };
    getFriendsRequests: {
        parameters: {
            query: {
                type: "incoming" | "outgoing" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            requester: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            addressee: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            status: string;
                            createdAt: Record<string, never> | string | number;
                        }[];
                        message: string;
                    };
                };
            };
        };
    };
    postFriendsRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    addresseeId: string;
                };
                "application/x-www-form-urlencoded": {
                    addresseeId: string;
                };
                "multipart/form-data": {
                    addresseeId: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            requester: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            addressee: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            status: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchFriendsByIdAccept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            requester: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            addressee: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            status: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchFriendsByIdDecline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            requester: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            addressee: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            status: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    deleteFriendsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    postFriendsInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    name: string;
                };
                "application/x-www-form-urlencoded": {
                    phone: string;
                    name: string;
                };
                "multipart/form-data": {
                    phone: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            requester: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            addressee: {
                                id: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                            };
                            status: string;
                            createdAt: Record<string, never> | string | number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getGroups: {
        parameters: {
            query?: {
                includeArchived?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            avatarUrl: (string | null) | null;
                            memberCount: number;
                            myBalance: number;
                            currency: string;
                        }[];
                        message: string;
                    };
                };
            };
        };
    };
    postGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    type: "trip" | "home" | "office" | "custom";
                    description?: string;
                    currency: string;
                    memberIds: string[];
                    /** @default true */
                    simplifyDebts?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name: string;
                    /** @enum {string} */
                    type: "trip" | "home" | "office" | "custom";
                    description?: string;
                    currency: string;
                    memberIds: string[];
                    /** @default true */
                    simplifyDebts?: boolean;
                };
                "multipart/form-data": {
                    name: string;
                    /** @enum {string} */
                    type: "trip" | "home" | "office" | "custom";
                    description?: string;
                    currency: string;
                    memberIds: string[];
                    /** @default true */
                    simplifyDebts?: boolean;
                };
            };
        };
        responses: never;
    };
    getGroupsJoinByToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getGroupsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            name: string;
                            type: string;
                            description: (string | null) | null;
                            currency: string;
                            avatarUrl: (string | null) | null;
                            simplifyDebts: boolean;
                            isAdmin: boolean;
                            members: {
                                id: string;
                                userId: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                                role: string;
                                balance: number;
                            }[];
                        };
                        message: string;
                    };
                };
            };
        };
    };
    deleteGroupsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchGroupsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    currency?: string;
                    avatarUrl?: string;
                    simplifyDebts?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    name?: string;
                    description?: string;
                    currency?: string;
                    avatarUrl?: string;
                    simplifyDebts?: boolean;
                };
                "multipart/form-data": {
                    name?: string;
                    description?: string;
                    currency?: string;
                    avatarUrl?: string;
                    simplifyDebts?: boolean;
                };
            };
        };
        responses: never;
    };
    postGroupsByIdMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    userIds: string[];
                };
                "application/x-www-form-urlencoded": {
                    userIds: string[];
                };
                "multipart/form-data": {
                    userIds: string[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    deleteGroupsByIdMembersByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchGroupsByIdMembersByUserIdRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    role: "admin" | "member";
                };
                "application/x-www-form-urlencoded": {
                    /** @enum {string} */
                    role: "admin" | "member";
                };
                "multipart/form-data": {
                    /** @enum {string} */
                    role: "admin" | "member";
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    postGroupsByIdInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default 168 */
                    expiresInHours?: number;
                };
                "application/x-www-form-urlencoded": {
                    /** @default 168 */
                    expiresInHours?: number;
                };
                "multipart/form-data": {
                    /** @default 168 */
                    expiresInHours?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            inviteUrl: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    deleteGroupsByIdInviteByInviteId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                page?: string;
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            type: string;
                            title: string;
                            body: (string | null) | null;
                            data: unknown;
                            readAt: ((Record<string, never> | string | number) | null) | null;
                            createdAt: Record<string, never> | string | number;
                        }[];
                        message: string;
                    };
                };
            };
        };
    };
    "getNotificationsUnread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            count: number;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    "patchNotificationsRead-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchNotificationsByIdRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getGroupsByIdExpenses: {
        parameters: {
            query?: {
                page?: string;
                limit?: string;
                category?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            paidBy: string;
                            paidByName: string;
                            paidByAvatar: (string | null) | null;
                            amount: string;
                            description: string;
                            category: string;
                            splitType: string;
                            date: string;
                            createdAt: string;
                            splits: {
                                userId: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                                owedAmount: string;
                            }[];
                        }[];
                        pagination: {
                            page: number;
                            limit: number;
                            total: number;
                            hasMore: boolean;
                        };
                    };
                };
            };
        };
    };
    postGroupsByIdExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: number;
                    description: string;
                    /** @enum {string} */
                    splitType: "equal" | "exact" | "percentage" | "itemized";
                    date: string;
                    paidBy?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    receiptUrl?: string;
                    receiptKey?: string;
                    notes?: string;
                };
                "application/x-www-form-urlencoded": {
                    amount: number;
                    description: string;
                    /** @enum {string} */
                    splitType: "equal" | "exact" | "percentage" | "itemized";
                    date: string;
                    paidBy?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    receiptUrl?: string;
                    receiptKey?: string;
                    notes?: string;
                };
                "multipart/form-data": {
                    amount: number;
                    description: string;
                    /** @enum {string} */
                    splitType: "equal" | "exact" | "percentage" | "itemized";
                    date: string;
                    paidBy?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    receiptUrl?: string;
                    receiptKey?: string;
                    notes?: string;
                };
            };
        };
        responses: never;
    };
    getGroupsByIdBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getExpensesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            id: string;
                            groupId: string;
                            paidBy: string;
                            paidByName: string;
                            paidByAvatar: (string | null) | null;
                            createdBy: string;
                            amount: string;
                            description: string;
                            category: string;
                            splitType: string;
                            receiptUrl: (string | null) | null;
                            date: string;
                            notes: (string | null) | null;
                            createdAt: string;
                            splits: {
                                id: string;
                                userId: string;
                                name: string;
                                avatarUrl: (string | null) | null;
                                owedAmount: string;
                                paidAmount: string;
                                percentage: (string | null) | null;
                            }[];
                            items: {
                                id: string;
                                name: string;
                                amount: string;
                                assignedTo: string[];
                            }[];
                        };
                        message: string;
                    };
                };
            };
        };
    };
    deleteExpensesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    patchExpensesById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount?: number;
                    description?: string;
                    /** @enum {string} */
                    splitType?: "equal" | "exact" | "percentage" | "itemized";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    date?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    notes?: string;
                };
                "application/x-www-form-urlencoded": {
                    amount?: number;
                    description?: string;
                    /** @enum {string} */
                    splitType?: "equal" | "exact" | "percentage" | "itemized";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    date?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    notes?: string;
                };
                "multipart/form-data": {
                    amount?: number;
                    description?: string;
                    /** @enum {string} */
                    splitType?: "equal" | "exact" | "percentage" | "itemized";
                    splits?: {
                        userId: string;
                        amount?: number;
                        percentage?: number;
                        items?: {
                            name: string;
                            amount: number;
                            assignedTo: string[];
                        }[];
                    }[];
                    date?: string;
                    /** @enum {string} */
                    category?: "food" | "travel" | "utilities" | "entertainment" | "shopping" | "health" | "accommodation" | "other";
                    notes?: string;
                };
            };
        };
        responses: never;
    };
    postExpensesReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "application/x-www-form-urlencoded": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            receiptUrl: string;
                            receiptKey: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
    getUsersMeBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getGroupsByIdSettle: {
        parameters: {
            query?: {
                page?: string;
                limit?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    postGroupsByIdSettle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    toUserId: string;
                    amount: number;
                    upiRef?: string;
                    note?: string;
                };
                "application/x-www-form-urlencoded": {
                    toUserId: string;
                    amount: number;
                    upiRef?: string;
                    note?: string;
                };
                "multipart/form-data": {
                    toUserId: string;
                    amount: number;
                    upiRef?: string;
                    note?: string;
                };
            };
        };
        responses: never;
    };
    deleteSettlementsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        success: true;
                        data: {
                            message: string;
                        };
                        message: string;
                    };
                };
            };
        };
    };
}
